// Well-known companion-planting pairings — a fun planner, not agronomic
// advice. Every good/bad reference points at another key in this same
// list, so the grid's neighbor check never dangles.
export const CROPS = [
  {
    key: "tomato",
    name: "Tomato",
    color: "#c0392b",
    goodWith: ["basil", "carrot", "onion"],
    badWith: ["potato", "corn", "squash"],
    sowNH: "Mar–May",
    harvestNH: "Jul–Sep",
    sowSH: "Sep–Nov",
    harvestSH: "Jan–Mar",
    growSeconds: 70,
  },
  {
    key: "basil",
    name: "Basil",
    color: "#4a7c3f",
    goodWith: ["tomato", "pepper"],
    badWith: [],
    sowNH: "Apr–Jun",
    harvestNH: "Jun–Sep",
    sowSH: "Oct–Dec",
    harvestSH: "Dec–Mar",
    growSeconds: 40,
  },
  {
    key: "carrot",
    name: "Carrot",
    color: "#d97e3a",
    goodWith: ["onion", "tomato", "lettuce", "beans"],
    badWith: [],
    sowNH: "Mar–Jul",
    harvestNH: "Jun–Oct",
    sowSH: "Sep–Jan",
    harvestSH: "Dec–Apr",
    growSeconds: 60,
  },
  {
    key: "onion",
    name: "Onion",
    color: "#8a6fa8",
    goodWith: ["carrot", "tomato", "lettuce", "pepper"],
    badWith: ["beans"],
    sowNH: "Mar–Apr",
    harvestNH: "Aug–Sep",
    sowSH: "Sep–Oct",
    harvestSH: "Feb–Mar",
    growSeconds: 55,
  },
  {
    key: "lettuce",
    name: "Lettuce",
    color: "#9bc26b",
    goodWith: ["carrot", "onion"],
    badWith: [],
    sowNH: "Mar–Aug",
    harvestNH: "May–Oct",
    sowSH: "Sep–Feb",
    harvestSH: "Nov–Apr",
    growSeconds: 45,
  },
  {
    key: "beans",
    name: "Beans",
    color: "#3f6b3f",
    goodWith: ["carrot", "corn", "squash"],
    badWith: ["onion"],
    sowNH: "May–Jun",
    harvestNH: "Jul–Sep",
    sowSH: "Nov–Dec",
    harvestSH: "Jan–Mar",
    growSeconds: 75,
  },
  {
    key: "corn",
    name: "Corn",
    color: "#e0b23c",
    goodWith: ["beans", "squash"],
    badWith: ["tomato"],
    sowNH: "May–Jun",
    harvestNH: "Aug–Sep",
    sowSH: "Nov–Dec",
    harvestSH: "Feb–Mar",
    growSeconds: 100,
  },
  {
    key: "squash",
    name: "Squash",
    color: "#c9781f",
    goodWith: ["corn", "beans"],
    badWith: ["tomato", "potato"],
    sowNH: "May–Jun",
    harvestNH: "Aug–Oct",
    sowSH: "Nov–Dec",
    harvestSH: "Feb–Apr",
    growSeconds: 110,
  },
  {
    key: "potato",
    name: "Potato",
    color: "#8a6a4a",
    goodWith: ["beans", "corn"],
    badWith: ["tomato", "squash"],
    sowNH: "Mar–May",
    harvestNH: "Jun–Sep",
    sowSH: "Sep–Nov",
    harvestSH: "Dec–Mar",
    growSeconds: 90,
  },
  {
    key: "pepper",
    name: "Pepper",
    color: "#cc4b3c",
    goodWith: ["basil", "onion"],
    badWith: [],
    sowNH: "Apr–Jun",
    harvestNH: "Jul–Sep",
    sowSH: "Oct–Dec",
    harvestSH: "Jan–Mar",
    growSeconds: 65,
  },
];

export const CROP_MAP = Object.fromEntries(CROPS.map((c) => [c.key, c]));

export const BED_SIZES = [
  { key: "small", label: "Small", cols: 4, rows: 3 },
  { key: "medium", label: "Medium", cols: 6, rows: 4 },
  { key: "large", label: "Large", cols: 8, rows: 5 },
];
